apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mintnodeapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mintnodeapp 
    spec:
      containers:
        - name: mintnodeapp 
          image: k8sgtmtraining.azurecr.io/mintnodeapp
          ports:
          - containerPort: 8080